org: lematosdev
app: cambios-altoque
service: cambios-altoque

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: personal
  layers:
    - ${env:CANVAS_LAYER}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            {
              'Fn::Join':
                [
                  '',
                  [
                    'arn:aws:s3:::${env:S3_BUCKET_NAME}',
                    '/*'
                  ]
                ]
            }
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - 'ses:*'
          Resource:
            - '*'

functions:
  create:
    handler: handler.createImage
  send:
    handler: handler.sendEmail
  fetch:
    handler: handler.fetchP2P

package:
  patterns:
    - '!node_modules/canvas/**'
    - 'assets/**'
